FROM migrate/migrate:v4.17.0

COPY server/migrations /migrations

ENTRYPOINT ["migrate", "-path", "/migrations", "-database"]
CMD ["postgres://sovereign:sovereign_dev@postgres:5432/sovereign?sslmode=disable", "up"]
