ALTER TABLE trades ALTER COLUMN investment_id DROP NOT NULL;
ALTER TABLE trades ALTER COLUMN investment_id SET DEFAULT NULL;
ALTER TABLE trades ALTER COLUMN user_id DROP NOT NULL;
ALTER TABLE trades ALTER COLUMN user_id SET DEFAULT NULL;
